# Generated by Django 5.2.12 on 2026-05-29 21:59

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(max_length=255, verbose_name='Заголовок приветствия')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок/Описание')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Главный баннер')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес театра')),
            ],
            options={
                'verbose_name': 'Главная страница и контакты',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('birthday', 'День рождения'), ('graduation', 'Выпускной')], max_length=20, verbose_name='Для какой страницы')),
                ('type', models.CharField(blank=True, choices=[('show', 'Шоу-программа'), ('interactive', 'Интерактивная программа')], max_length=20, null=True, verbose_name='Тип программы')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Картинка программы')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'db_table': 'main_program',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('roles', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None, verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('birthday', 'День рождения'), ('graduation', 'Выпускной'), ('spectacle', 'Спектакль')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('features_list', models.TextField(verbose_name='Список услуг')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tariffs/', verbose_name='Картинка тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'tariff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('birthday', 'День рождения'), ('graduation', 'Выпускной'), ('spectacle', 'Спектакль')], max_length=20, verbose_name='Категория')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='Возраст детей')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Время события')),
                ('guests_count', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во гостей')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('chosen_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps_program', to='main.program', verbose_name='Интерактивная программа')),
                ('chosen_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps_show', to='main.program', verbose_name='Шоу-программа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('members', models.ManyToManyField(related_name='groups', to='main.staff', verbose_name='Члены группы')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Постер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staffgroup', verbose_name='Назначенная команда')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'main_event',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Заявка')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Репертуарный спектакль')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='Сотрудник')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staffgroup', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника',
                'verbose_name_plural': 'Назначения сотрудников',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='main.staffgroup', verbose_name='Назначенная команда'),
        ),
        migrations.AddField(
            model_name='application',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tariff', verbose_name='Выбранный тариф'),
        ),
    ]
