# Generated by Django 5.2.12 on 2026-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('graduation', 'Выпускной'), ('spectacle', 'Спектакль')], default='birthday', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features_list',
            field=models.TextField(help_text='Список услуг через перенос строки'),
        ),
    ]
