# Generated by Django 5.2.12 on 2026-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
