# Generated by Django 5.2.12 on 2026-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на билеты'),
        ),
    ]
