# Generated by Django 5.2.12 on 2026-05-15 10:56

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_staff_role_staff_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='roles',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None, verbose_name='Роли'),
        ),
    ]
