# Generated by Django 5.2.12 on 2026-05-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Репертуарный спектакль'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Заявка (частная)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staffgroup', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='Сотрудник'),
        ),
    ]
