# Generated by Django 6.0.3 on 2026-05-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignment_event_alter_assignment_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application', verbose_name='Заявка'),
        ),
    ]
