# Generated by Django 5.2.12 on 2026-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_options_remove_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='event_date_time',
        ),
        migrations.AddField(
            model_name='application',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
        migrations.AddField(
            model_name='application',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время события'),
        ),
    ]
