# Generated by Django 5.2.12 on 2026-05-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assignment_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staffgroup', verbose_name='Назначенная команда'),
        ),
    ]
