# Generated by Django 6.0.3 on 2026-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_application_event_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница и контакты'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес театра'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Главный баннер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.TextField(verbose_name='Подзаголовок/Описание'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='welcome_text',
            field=models.CharField(max_length=255, verbose_name='Заголовок приветствия'),
        ),
    ]
