# Generated by Django 6.0.3 on 2026-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_homepage_options_homepage_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('birthday', 'День рождения'), ('graduation', 'Выпускной')], max_length=20, verbose_name='Для какой страницы')),
                ('type', models.CharField(choices=[('show', 'Шоу-программа'), ('interactive', 'Интерактивная программа')], max_length=20, verbose_name='Тип программы')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
