# Generated by Django 5.2.12 on 2026-04-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_application_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tariff', verbose_name='Выбранный тариф'),
        ),
    ]
