# Generated by Django 6.0.3 on 2026-05-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_application_assigned_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='assigned_group',
        ),
    ]
