# Generated by Django 6.0.3 on 2026-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_program_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'managed': True, 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='tariff',
            name='duration',
            field=models.CharField(default='', max_length=100, verbose_name='Длительность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tariffs/', verbose_name='Картинка тарифа'),
        ),
        migrations.AlterModelTable(
            name='tariff',
            table='main_tariff',
        ),
    ]
