# Generated by Django 6.0.3 on 2026-05-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_application_assigned_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='main.staffgroup', verbose_name='Назначенная команда'),
        ),
    ]
