# Generated by Django 5.2.12 on 2026-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_application_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='birthday_info',
            field=models.TextField(blank=True, verbose_name='Общая информация о Днях Рождения (внизу страницы)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Длительность (напр. НА 3 ЧАСА)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tariffs/', verbose_name='Картинка тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features_list',
            field=models.TextField(verbose_name='Список услуг (каждая с новой строки)'),
        ),
    ]
