# Generated by Django 5.2.12 on 2026-04-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homepage_birthday_info_tariff_duration_tariff_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('show', 'Шоу-программа'), ('program', 'Интерактивная программа')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entertainment/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Шоу или Программа',
                'verbose_name_plural': 'Шоу и Программы',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_program',
            field=models.CharField(blank=True, max_length=255, verbose_name='Выбранная программа'),
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_show',
            field=models.CharField(blank=True, max_length=255, verbose_name='Выбранное шоу'),
        ),
    ]
