# Generated by Django 6.0.3 on 2026-05-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tariff_options_tariff_duration_tariff_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tariff',
            table='tariff',
        ),
    ]
