# Generated by Django 5.2.12 on 2026-04-24 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_entertainmentitem_application_chosen_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='chosen_program',
        ),
        migrations.RemoveField(
            model_name='application',
            name='chosen_show',
        ),
        migrations.AddField(
            model_name='application',
            name='entertainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.entertainmentitem', verbose_name='Шоу/Программа'),
        ),
        migrations.AddField(
            model_name='application',
            name='guests_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во гостей'),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Возраст детей'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tariff', verbose_name='Выбранный тариф'),
        ),
    ]
