# Generated by Django 6.0.3 on 2026-05-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tariff_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps_program', to='main.program', verbose_name='Интерактивная программа'),
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps_show', to='main.program', verbose_name='Шоу-программа'),
        ),
        migrations.AddField(
            model_name='application',
            name='guests_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во гостей'),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Возраст детей'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('graduation', 'Выпускной'), ('spectacle', 'Спектакль')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tariff', verbose_name='Выбранный тариф'),
        ),
    ]
