# Generated by Django 5.2.12 on 2026-04-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_application_chosen_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='entertainment',
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps_program', to='main.entertainmentitem', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps_show', to='main.entertainmentitem', verbose_name='Шоу'),
        ),
    ]
