# Generated by Django 6.0.3 on 2026-05-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_application_options_application_chosen_program_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='main_event',
        ),
    ]
