# Generated by Django 6.0.3 on 2026-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(blank=True, choices=[('show', 'Шоу-программа'), ('interactive', 'Интерактивная программа')], max_length=20, null=True, verbose_name='Тип программы'),
        ),
        migrations.AlterModelTable(
            name='program',
            table='main_entertainmentitem',
        ),
    ]
