# Generated by Django 6.0.3 on 2026-05-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_program_type_alter_program_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'managed': True, 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelTable(
            name='program',
            table='main_program',
        ),
    ]
